---
name: Docker Image CI
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        snapcast:
          - image_name: pixoo-rest
            dockerfile_name: Dockerfile

    env:
      IMAGE_NAMESPACE: nolte

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          buildx-version: latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Determine tag
        id: imagetag
        run: |
          echo "::set-output name=image_tag::${GITHUB_REF#refs/tags/}"

      - name: Build and push container image
        run: |
          docker buildx build \
            -t "${IMAGE_NAMESPACE}/${{ matrix.snapcast.image_name }}:latest" \
            -t "${IMAGE_NAMESPACE}/${{ matrix.snapcast.image_name }}:${{ steps.imagetag.outputs.image_tag }}" \
            --platform linux/amd64,linux/arm/v7 \
            --push \
            -f ${{ matrix.snapcast.dockerfile_name }} \
            .
